export interface DevisAutoModel {
      id_client:string,
      Nom:string,
      Prenom : string,
      Adresse:string,
      Num_Client:string | null ,
      Telephone_Fix:string,
      Telephone_Mobile:string,
      Email:string,
      Situation_Familial:string,
      Nombre_Enfants_Inférieur_16ans:string,
      Nombre_Enfants_Superieur_16ans:string,
      Profession:string,
      Date_Naissance:string,
      Date_Permis_Conduite:string
      Marque_D1:string,
      Modele_D3:string,
      Version:string,
      Puissance_Fiscale:string,
      Type_Mine_D2:string,
      Mise_Circulation_B:string,
      Immatriculation:string,
      Date_Acquisition:string,
      Titulaire_Carte_Grise:string,
      Autres_Conducteurs:string,
      Coefficient_Bonus_CRM:string,
      Date_Obtention_CRM:string,
      Nature_Sinistre_1:string | null,
      Date_Sinistre_1:string | null,
      Nature_Sinistre_2:string | null,
      Date_Sinistre_2:string | null,
      Nature_Sinistre_3:string | null,
      Date_Sinistre_3:string | null,
      Resiliation_Compagnie:string,
      Motif_Resiliation:string,
      Date_Resiliation:string,
      Suspension_ou_Annulation_Permis:string,
      dateSuspens:string,
      Date_Motif_Suspension:string,
      Garage: Array<string>,
      Usage_Vehiculaire: Array<string>,
      Garanties_Souhaitées: Array<string>,
      Option: Array<string>,
      Mode_Paiement: Array<string>,
      uid:string,
      
}