export interface DevisProModel{
    Nom_Entreprise:string,
    Adresse:string,
    id_Client:string,
    Nom:string,
    Prenom : string,
    Forme_Juridique: string,
    Date_Naiss: string,
    Telephone_Fix:string,
    Telephone_Mobile:string,
    Email:string,
    Siret:string,
    APE:string,
    Activite_Principal:string,
    Ratio_Principal:string,
    Activite_AnnexeOne:string,
    Ratio_AnnexeOne:string,
    Activite_AnnexeTwo:string,
    Ratio_AnnexeTwo:string,
    Activite_AnnexeThree:string,
    Ratio_AnnexeThree:string,
    Activite_AnnexeFour:string,
    Ratio_AnnexeFour:string,
    Activite_AnnexeFive:string,
    Ratio_AnnexeFive:string,
    Nom_Conjoint:string,
    Prenom_Conjoint:string,
    Conjoint_Collaborateur:string,
    Date_Naiss_Conjoint:string,
    Chiffre_Affaire:string,
    Effectif:string,
    Surface:string,
    Produits_Dangereux:string,
    Nature_Produits:string,
    Garanties_Souhaitées:Array<string>,
    Autres_Garanties:string,
    Options:Array<string>,
    Autres_Options:string,
    Mode_Paiements:Array<string>,
    dateRegister:string | null,
    typeDevis:string,
    uid:string,
}